version: '3.5'

volumes:
  mongo_vol:

services:
  web:
    image: amatildes/rotten-potatoes:v20
    build: 
      dockerfile: Dockerfile
      context: ./src/
    ports:
      - 8080:5000
    environment:
    - MONGODB_DB=admin
    - MONGODB_HOST=mongodb
    - MONGODB_PORT=27017
    - MONGODB_USERNAME=mongouser
    - MONGODB_PASSWORD=mongopwd

  mongodb:
    image: mongo:5.0.0
    volumes:
      - mongo_vol:/data/db
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mongouser
    - MONGO_INITDB_ROOT_PASSWORD=mongopwd    
      
networks:
  default:
    name: mongo